ALTER TABLE `batch`
        CHANGE COLUMN `id` `batch_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	CHANGE COLUMN `name` `batch_external_id` VARCHAR(50) NOT NULL DEFAULT '0' AFTER `batch_id`,
	CHANGE COLUMN `description` `batch_description` LONGTEXT NOT NULL AFTER `batch_external_id`,
	CHANGE COLUMN `active` `is_batch_active` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' AFTER `date`,
	CHANGE COLUMN `property_owner_id` `batch_property_owner_id` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `batch_external_id`,
	CHANGE COLUMN `sequence_id` `batch_sequence_id` INT(11) UNSIGNED NOT NULL DEFAULT '0' AFTER `batch_property_owner_id`,
	CHANGE COLUMN `collection_id` `mapto_collections` VARCHAR(255) AFTER `batch_property_owner_id`;
ALTER TABLE `batch`
   ADD COLUMN `nid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
   ADD COLUMN `batch_default_perm_notes` LONGTEXT NOT NULL,
   ADD COLUMN `batch_default_CR_holder` LONGTEXT NOT NULL,
   ADD COLUMN `structural_metadata_treatment` LONGTEXT NOT NULL,
   ADD COLUMN `image_editing_treatment` LONGTEXT NOT NULL,
   ADD COLUMN `blank_and_missing_treatment` LONGTEXT NOT NULL,
   ADD COLUMN `page_edge_treatment` LONGTEXT NOT NULL,
   ADD COLUMN `batch_condition_handling` LONGTEXT NOT NULL,
   ADD COLUMN `use_color_target` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
   ADD COLUMN `is_batch_request` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
   ADD COLUMN `has_file` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
   ADD COLUMN `batch_item_type_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
   ADD COLUMN `new_or_existing` VARCHAR(20) NOT NULL DEFAULT '0' COMMENT 'new or existing Collection',
   ADD COLUMN `default_genre` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `default_type_of_resource` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `default_depositor` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `default_ead_id` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `default_voyager_id` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `batch_default_pub_status` VARCHAR(12) NOT NULL DEFAULT '',
   ADD COLUMN `output_target_size` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `image_color_type_and_bitdepth` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `image_resolution` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `file_naming_scheme` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `file_type` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `batch_request_due_date` TIMESTAMP NULL DEFAULT NULL,
   ADD COLUMN `batch_requestor` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `batch_source_identifier` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `batch_priority` VARCHAR(50) NOT NULL DEFAULT '',
   ADD COLUMN `batch_default_CR_status` VARCHAR(12) NOT NULL DEFAULT '',
   ADD COLUMN `content_type_id` INT(5) UNSIGNED NOT NULL DEFAULT '0',
   ADD COLUMN `mapto_site_id_values` VARCHAR(255) NOT NULL DEFAULT '0' COMMENT 'comma separated values',
   ADD COLUMN `file` VARCHAR(255) NOT NULL DEFAULT '0',
   ADD COLUMN `lastmod` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `file`,
   ADD COLUMN `user` VARCHAR(50) NOT NULL AFTER `lastmod`;
UPDATE `batch` set `user` = 'migrate script';
