ALTER TABLE `transaction_temp`
  ADD COLUMN `transaction_action_id` INT(11) NOT NULL AFTER `user_id`;

UPDATE transaction_temp SET `transaction_action_id` = 1 WHERE description = 'check-in completed';
UPDATE transaction_temp SET `transaction_action_id` = 2 WHERE description = 'scan completed';
UPDATE transaction_temp SET `transaction_action_id` = 3 WHERE description = 'ingest completed';
UPDATE transaction_temp SET `transaction_action_id` = 4 WHERE description = 'prep for bodybuilder completed';
UPDATE transaction_temp SET `transaction_action_id` = 5 WHERE description = 'structural metadata completed';
UPDATE transaction_temp SET `transaction_action_id` = 6 WHERE description = 'make pdf completed';
UPDATE transaction_temp SET `transaction_action_id` = 10 WHERE description = 'check-out completed';
UPDATE transaction_temp SET `transaction_action_id` = 12 WHERE description = 'make thumbnail completed';
UPDATE transaction_temp SET `transaction_action_id` = 13 WHERE description = 'prepare macrob files completed';
UPDATE transaction_temp SET `transaction_action_id` = 14 WHERE description = 'ocr completed';
UPDATE transaction_temp SET `transaction_action_id` = 16 WHERE description = 'make jpg completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 101 WHERE description = 'make jpg2000 completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 102 WHERE description = 'make macrob csv completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 103 WHERE description = 'deliver to webserver completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 104 WHERE description = 'release online completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 105 WHERE description = 'make zoomify completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 106 WHERE description = 'make xml completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 107 WHERE description = 'make DLXS textclass derivatives completed';
UPDATE `transaction_temp` SET `transaction_action_id` = 108 WHERE description = 'item record created';
UPDATE `transaction_temp` SET `transaction_action_id` = 109 WHERE description = 'migrated record from 1st gen workflow';
UPDATE `transaction_temp` SET `transaction_action_id` = 110 WHERE description = 'derivatives';
UPDATE `transaction_temp` SET `transaction_action_id` = 111 WHERE description = 'xml';
UPDATE `transaction_temp` SET `transaction_action_id` = 112 WHERE description = 'online';
UPDATE `transaction_temp` SET `transaction_action_id` = 113 WHERE description = 'delivered';
UPDATE `transaction_temp` SET `transaction_action_id` = 114 WHERE description = 'ocr';
UPDATE `transaction_temp` SET `transaction_action_id` = 115 WHERE description = 'ingestIntoRepository';
UPDATE `transaction_temp` SET `transaction_action_id` = 116 WHERE description = 'prepForMetadata';
UPDATE `transaction_temp` SET `transaction_action_id` = 117 WHERE description = 'reset status';
UPDATE `transaction_temp` SET `transaction_action_id` = 118 WHERE description = 'loadRecord';
UPDATE `transaction_temp` SET `transaction_action_id` = 119 WHERE description = 'checkIn';
UPDATE `transaction_temp` SET `transaction_action_id` = 120 WHERE description = 'stopScanGray';
UPDATE `transaction_temp` SET `transaction_action_id` = 121 WHERE description = 'stopBR';
UPDATE `transaction_temp` SET `transaction_action_id` = 122 WHERE description = 'stopMeta';
UPDATE `transaction_temp` SET `transaction_action_id` = 123 WHERE description = 'startMeta';
UPDATE `transaction_temp` SET `transaction_action_id` = 124 WHERE description = 'startScanGray';
UPDATE `transaction_temp` SET `transaction_action_id` = 125 WHERE description = 'startBR';
UPDATE `transaction_temp` SET `transaction_action_id` = 126 WHERE description = 'exported files from repository to problems directory';
UPDATE `transaction_temp` SET `transaction_action_id` = 127 WHERE description = 'preport';
UPDATE `transaction_temp` SET `transaction_action_id` = 128 WHERE description = 'presolve';
UPDATE `transaction_temp` SET `transaction_action_id` = 129 WHERE description = 'checkOut';
UPDATE `transaction_temp` SET `transaction_action_id` = 130 WHERE description = 'resetItemStatus';
UPDATE `transaction_temp` SET `transaction_action_id` = 131 WHERE description = 'stopProblem';
UPDATE `transaction_temp` SET `transaction_action_id` = 132 WHERE description = 'stopScanColor';
UPDATE `transaction_temp` SET `transaction_action_id` = 133 WHERE description = 'startScanColor';
UPDATE `transaction_temp` SET `transaction_action_id` = 134 WHERE description = 'stopScanFoldouts';
UPDATE `transaction_temp` SET `transaction_action_id` = 135 WHERE description = 'startScanFoldouts';
UPDATE `transaction_temp` SET `transaction_action_id` = 136 WHERE description = 'unknown';
UPDATE `transaction_temp` SET `transaction_action_id` = 137 WHERE description = 'problem reported';
UPDATE `transaction_temp` SET `transaction_action_id` = 138 WHERE description = 'problem resolved';
UPDATE `transaction_temp` SET `transaction_action_id` = 139 WHERE description = 'structural metadata performed';
UPDATE `transaction_temp` SET `transaction_action_id` = 140 WHERE description = 'setReScan';
UPDATE `transaction_temp` SET `transaction_action_id` = 141 WHERE description = 'scan performed';
UPDATE `transaction_temp` SET `transaction_action_id` = 142 WHERE description = 'make thumnail performed';
UPDATE `transaction_temp` SET `transaction_action_id` = 143 WHERE description = 'check-out performed';
UPDATE `transaction_temp` SET `transaction_action_id` = 144 WHERE description = 'ocr performed';

ALTER TABLE `transaction_temp` DROP COLUMN `description`;

