INSERT INTO `transaction_actions` (`id`, `description`) VALUES
	(1, 'check-in completed'),
	(2, 'scan completed'),
	(3, 'ingest completed'),
	(4, 'prep for bodybuilder completed'),
	(5, 'structural metadata completed'),
	(6, 'make pdf completed'),
	(10, 'check-out completed'),
	(12, 'make thumbnail completed'),
	(13, 'prepare macrob files completed'),
	(14, 'ocr completed'),
	(16, 'make jpg completed'),
	(101, 'make jpg2000 completed'),
	(102, 'make macrob csv completed'),
	(103, 'deliver to webserver completed'),
	(104, 'release online completed'),
	(105, 'make zoomify completed'),
	(106, 'make xml completed'),
	(107, 'make DLXS textclass derivatives completed'),
	(108, 'item record created'),
	(109, 'migrated record from 1st gen workflow'),
	(110, 'derivatives'),
	(111, 'xml'),
	(112, 'online'),
	(113, 'delivered'),
	(114, 'ocr'),
	(115, 'ingestIntoRepository'),
	(116, 'prepForMetadata'),
	(117, 'reset status'),
	(118, 'loadRecord'),
	(119, 'checkIn'),
	(120, 'stopScanGray'),
	(121, 'stopBR'),
	(122, 'stopMeta'),
	(123, 'startMeta'),
	(124, 'startScanGray'),
	(125, 'startBR'),
	(126, 'exported files from repository to problems directory'),
	(127, 'preport'),
	(128, 'presolve'),
	(129, 'checkOut'),
	(130, 'resetItemStatus'),
	(131, 'stopProblem'),
	(132, 'stopScanColor'),
	(133, 'startScanColor'),
	(134, 'stopScanFoldouts'),
	(135, 'startScanFoldouts'),
	(136, 'unknown'),
	(137, 'problem reported'),
	(138, 'problem resolved'),
	(139, 'structural metadata performed'),
	(140, 'setReScan'),
	(141, 'scan performed'),
	(142, 'make thumnail performed'),
	(143, 'check-out performed'),
	(144, 'ocr performed');
